### ISSUE TITLE
Serialize / deserialize array didn't keep order

### ISSUE THREAD

**Issue by Maxouhell** [shakilsiraj/json-object-mapper#12]
Hi !

If you deserialize a JSON inside an object, and then serialize it, array order are not keeped.

For example 
```
{
    "test": [1,2,3,4,5]
}
```

can become 
```
{
    "test": [2,1,5,4,3]
}
```

I think the problem comes from `uniqueId()` inside `SerializeArrayType` method.
Could you check it ?

Thanks

**Comment by Maxouhell** [comment]
Up !

**Comment by shakilsiraj** [comment]
Please try release 1.5
