### ISSUE TITLE
Custom Serializer / Deserialiser caching does not work with Generic Classes / minimised bundles

### ISSUE THREAD

**Issue by ironchimp** [shakilsiraj/json-object-mapper#2]
Hi,

firstly, thanks for the library - it fits my needs perfectly, however I have encountered a couple of blockers related to the caching of custom de/serializer objects.

From my debugging, it seems that the caching logic uses a function over the string representation of the instantiation method  of de/serializer. Under the following circumstances, this results in the incorrect de/serializer being used:

### 1. Generic classes as custom de/serializers
As I use a lot of ES6 Maps / Sets in my project, I wrote a generic marshalling class to deal with the de/serialisation of the collection. However, the identifier used for the entry into the cache map does not include the generic type specifier.

Example:
Given the following generic Set deserializer definition:
```typescript
export class SetMarshaller<EntryType> implements Deserializer, Serializer {
  type: {new (): EntryType};

  public constructor(type: {new (): EntryType}) {
    this.type = type;
  }

  public deserialize(values: string[]): Set<EntryType> {
    const setToReturn: Set<EntryType> = new Set();
    if (values) {
      values.forEach(entry => {
        setToReturn.add(ObjectMapper.deserialize(this.type, entry));
      });
    }
    return setToReturn;
  }

  public serialize(value: Set<EntryType>): string {
    const results = [];
    value.forEach(entry => {
      let obj: any = entry;
      if (isObject(entry)) {
        obj = ObjectMapper.serialize(entry).toString();
      }
      results.push(JSON.parse(obj));
    });
    return JSON.stringify(results);
  }

}
```

Both of the following instantiations will result in the same identifier being used in the cache map:
```typescript
SetMarshaller<MyCusomObject1>;  // identifier: 'SetMarshaller'
SetMarshaller<YetAnotherCustomObject>; // identifier: 'SetMarshaller'
```

This will result in every set marshaller using the instanced used for the first encountered SetMashaller during execution of the app.

### 2. Production builds under Angular CLI
The identity mechanism shows interesting behaviour when running a production build generated by angular-cli.

Specifically, the minification and uglification mechanism replaces the named constructors with generated functions, which obscures the actual name of the construction function, resulting in more frequent clashes in the caching mechanism.

### Request
Is it possible to implement some way to allow my de/serializer implementations to specify their own identify function?

Thanks,
Paul Wallace

**Comment by shakilsiraj** [comment]
Hi there,

I see what you mean. I can give you two options -  I can either add a class decorator or add an optional entry into @JsonProperty decorator. Either of which will not result in a breaking build. What's your thoughts on that?

Thanks, Shakil

**Comment by ironchimp** [comment]
I think a class decorator may be cleaner, as this is more a function of the
marshaller object as opposed to how to marshal the data.

However, the additional field in the JsonProperty is more explicit, which
makes for easier discovery of the functionality.

Ultimately, either option is viable, but i would suggest you pick the one
that is consistent with your overall design of the library.

Thanks,
Paul

**Comment by shakilsiraj** [comment]
Hi Paul,

Can you please upgrade to v 1.4.0 to test out the class decorator @CacheKey? This should solve the problem. Here is an example:

```
@CacheKey("TestSerializerDeserializerCacheKey")
class TestSerializerDeserializer implements Serializer, Deserializer {
  deserialize = (value: any): any => {

            }
            serialize = (value: any): any => {

            }
        }

        let instance: TestSerializerDeserializer = getOrCreateDeserializer(TestSerializerDeserializer);
        expect(deserializers["TestSerializerDeserializerCacheKey"]).toBeDefined();
        expect(deserializers["TestSerializerDeserializerCacheKey"]).toBe(instance);

        instance = getOrCreateSerializer(TestSerializerDeserializer);
        expect(serializers["TestSerializerDeserializerCacheKey"]).toBeDefined();
        expect(serializers["TestSerializerDeserializerCacheKey"]).toBe(instance);
```

**Comment by ironchimp** [comment]
Hi,

The decorator function works well, thanks!

Paul
