### ISSUE TITLE
Cannot use objects with an existing constructor?

### ISSUE THREAD

**Issue by lookfirst** [shakilsiraj/json-object-mapper#27]
```
interface Result {
	success: boolean;
	message: string;
	result: {} | {}[];
}

class ResultData implements Result {
	// success: boolean;
	// message: string;
	// result: {} | {}[];
	constructor(public success: boolean, public message: string, public result: {} | {}[]) {}
}
```

But I get a compile error because you expect a `constructor() {}` to be available.

```
Argument of type 'typeof ResultData' is not assignable to parameter of type 'new () => ResultData'.
```

I guess one could argue that I don't need an interface for my data classes.

**Comment by shakilsiraj** [comment]
You could make those parameters optional. Here is an example:

it('Testing interface based class', () => {

        interface Result {
            success?: boolean;
            message?: string;
            result?: {} | {}[];
        }

        class ResultData implements Result {
            constructor(public success?: boolean, public message?: string,  public result?: {}[]) {

            }
        }

        const json = {success: true, message: 'this is a test', result: {one: 1}};
        const instance: Result = ObjectMapper.deserialize(ResultData, json);
        expect(instance.message).toBe('this is a test');
        expect(instance.success).toBeTruthy();
        expect(instance.result).toBeDefined();

    });

Instead of Interface, can't you extend from a base class? Decorators don't work with interfaces.

**Comment by lookfirst** [comment]
Ok, you're right. Thanks!

Interface is my stupid in this case. I'm not extending these data classes or providing alternate implementations of them. I don't need the interface.
