### ISSUE TITLE
Deserialize quoted floats

### ISSUE THREAD

**Issue by Qrzy** [shakilsiraj/json-object-mapper#29]
There seems to be a problem with deserializing floats:

```typescript
class Test {
    @JsonProperty({ name: 'test_test' }) test: number = 0.00;
}
```
```typescript
const data = { test_test: '1.234' };
const testData: Test = ObjectMapper.deserialize(Test, data);
console.log(testData);
```

Outputs:
```typescript
Test { test: "1.234" }
```

**Comment by artonio** [comment]
But it looks like your 'test_test' var is holding a string (1.234 is surrounded with quotes, which makes it a string), try this: 
`const data = { test_test: 1.234 };`

**Comment by artonio** [comment]
Here is the full unit test which passes.
```
it('Deseralize float', () => {
        class Test {
            @JsonProperty({ name: 'test_test' }) 
            test: number = 0.00;
        }

        const data = { test_test: 1.234 };
        const testData: Test = ObjectMapper.deserialize(Test, data);
        expect(testData.test).toBe(1.234);
    });
```

**Comment by Qrzy** [comment]
True, but this is what we get from the API.
And even in case of data from pure .json file it would be surrounded by quotes (double in that case) too.
Shouldn't this be mapped according to types of the class properties?

**Comment by artonio** [comment]
This is not true, JSON data can hold the following: number (without quotes), strings (with quotes), booleans (false/true without quotes), other JSON objects and arrays. However, if you are getting a number as a string from some API, the following code should help you deserialize the way you want:

 ```
it('Deseralize float passed as string', () => {
        class StringToFloatDeserializer implements Deserializer {
            deserialize = (value: string): number => {
                return parseFloat(value);
            }
        }
        class Test {
            @JsonProperty({ name: 'test_test', serializer: StringToFloatDeserializer}) 
            test: number = 0.00;
        }

        const data = { test_test: '1.234' };
        const testData: Test = ObjectMapper.deserialize(Test, data);
        expect(testData.test).toBe(1.234);
    });
```

**Comment by Qrzy** [comment]
I see, so there is no way to determine this on the level of this mapper and I need to pass my own (de)serializer. Correct?

**Comment by artonio** [comment]
Yes. But I can understand why one would think that by explicitly defining a variable in TypeScript of type number and passing a string to it and expecting it to be a number because TypeScript promises to be type safe. We ran into a similar issue with Angular.

**Comment by Qrzy** [comment]
Just wondering... Would it be possible to preconfigure mapper for the whole project assigning a (de)serializer for certain types? Just to avoid providing the (de)serializer (for numbers in quotes for example) on each and every occurance of them in mapped classes.

**Comment by artonio** [comment]
Not that I know of
