### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by futaroAqp** [shakilsiraj/json-object-mapper#3]
I am replicating the example class from the wiki page:
import {JsonProperty} from 'json-object-mapper';
export class SimpleRoster {
     private worksOnWeekend: Boolean = undefined;
    @JsonProperty({type: Date})
    private systemDate: Date = undefined;
    public isAvailableToday(): Boolean {
        if (this.systemDate.getDay() % 6 === 0 && this.worksOnWeekend === false) {
            return false;
        }
        return true;
    }

}
but i get this:
.../node_modules\json-object-mapper\dist\ObjectMapper.es2015.js:1
(function (exports, require, module, __filename, __dirname) { import 'reflect-metadata';

is this the correct way?

**Comment by shakilsiraj** [comment]
Can you please provide a plukr or something similar example? Thanks.

**Comment by DeliciousPickle** [comment]
+1 with this problem.  Is there some other dependency?

`▶ node
> require('json-object-mapper')
/usr/local/lib/node_modules/json-object-mapper/dist/ObjectMapper.es2015.js:1
(function (exports, require, module, __filename, __dirname) { import 'reflect-metadata';
                                                              ^^^^^^
SyntaxError: Unexpected token import
`

**Comment by shakilsiraj** [comment]
@DeliciousPickle are u trying running directly on node? 

if so, i don't think it's going to work as this is a typescript library. May I suggest looking into .. http://brianflove.com/2016/11/08/typescript-2-express-node/ ?

**Comment by marcellobarile** [comment]
I'm getting a different error message which might have the same root cause, more specifically, when I run a JEST test suite which uses a model, mapped with the json-object-mapper, the error I get is:

```
{blablabla}/node_modules/json-typescript-mapper/libs/utils.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export function isTargetType(val:any, type:"object" | "string"):boolean {
^^^^^^
SyntaxError: Unexpected token export
```

I've already webpack set up, TS transpilation works just fine for all the other files.
