### ISSUE TITLE
Compatibility With Node

### ISSUE THREAD

**Issue by sidd-s** [shakilsiraj/json-object-mapper#5]
Hi,

Awesome work here, pretty much similar to Java jakson library. 

One quick question, at this point does this module supported on Node? . I think ES6 features being used here, so just want to check on this. Please share your thoughts

**Comment by shakilsiraj** [comment]
Hi there,

Sorry about the delayed reply, I was not looking at this for a while.

Yes, you can't use it directly as it is a typescript project. The main problem are the decorators and how they are compiled into ES5. Without the compiler from typescript, it's kinda very hard thing to do. Just compare what becomes the output:

` class TagLib {
            @JsonProperty("taglib-uri")
            tagLibUri: String = undefined;
            @JsonProperty("taglib-location")
            tagLibLocation: String = undefined;

        }     `

vs
`var TagLib = (function () {
            function TagLib() {
                this.tagLibUri = undefined;
                this.tagLibLocation = undefined;
            }
            return TagLib;
        }());
        __decorate([
            DecoratorMetadata_1.JsonProperty("taglib-uri"),
            __metadata("design:type", String)
        ], TagLib.prototype, "tagLibUri", void 0);
        __decorate([
            DecoratorMetadata_1.JsonProperty("taglib-location"),
            __metadata("design:type", String)
        ], TagLib.prototype, "tagLibLocation", void 0);
        }());`

If you are not going to use the decorators there is not much you can get out of this library. 

But you can NodeJs + TypeScript development principles if you want to use it, here is a good example that I have seen so far - [TypeScript 2 + Express + Node.js.](http://brianflove.com/2016/11/08/typescript-2-express-node/)

I guess you will have to do the same as if you are using it as a ES5 browser project :).

Thanks for your kind words.
