### ISSUE TITLE
Function deserialize

### ISSUE THREAD

**Issue by doctore** [shakilsiraj/json-object-mapper#8]
Hi

I have found several "problems" related with the function `deserialize`:

**1.** If you want to deserialize to a DTO, you should initialize all properties of the object. That is:

```
class SimpleRoster {
    private name: String;
    private worksOnWeekend: Boolean;
}
```
It doesn't work correctly, you should to include default values in all properties:

```
class SimpleRoster {
    private name: String = undefined;
    private worksOnWeekend: Boolean = undefined;
}
```

**2.** It is not possible to work with your "custom constructor":

```
export class InvoiceDetail {
  constructor (private concept: string, private numberOfItems: number
              ,private cost: number) {}
}

export class Invoice {
  constructor (private identifier: string, private month: number, private year: number
              ,private detail: InvoiceDetail[]) {}
}
```

Reading the definition of the `ObjectMapper.deserialize`, this function only works with objects that have an "empty constructor" however, in this case, it implies that I should include "a lot of" boilerplate code.

Is there an option and/or way to deserialize a json string into objects of those classes (or similar classes) without to remove current constructors? (not always the "source" of those objects will be a Json string).

Thanks in advance

**Comment by doctore** [comment]
Hi

Working with Typescript (watching the JS generated and so on) I have seen why you have done it in that way. So, if you want, you can close this issue. The "problems" described above are generated by TS.

Thanks

**Comment by shakilsiraj** [comment]
No worries.
